// === GENERATED by generate_boat_profile.py on 2026-06-16 10:38:13 ===
// profile: default-displacement   hull: displacement
// DO NOT EDIT BY HAND -- regenerate from the boat spec instead.
//
// Derived performance estimates (see the .c file header for full report):
//   hull speed         :   1.25 m/s (  2.4 kn)
//   prop-limited max   :   4.72 m/s (  9.2 kn)
//   recommended max    :   1.38 m/s (  2.7 kn)
//   Froude @ max       :   0.44

#ifndef BOAT_PROFILE_H
#define BOAT_PROFILE_H

#include <stdint.h>
#include <stdbool.h>

// ---------------------------------------------------------------------------
// Compile-time tuning constants (usable from C and C++/.ino).
// ---------------------------------------------------------------------------
#define BP_PROFILE_NAME            "default-displacement"
#define BP_HULL_TYPE               "displacement"

// -- servo / rudder --
#define BP_SERVO_US_MIN            1100
#define BP_SERVO_US_CENTER         1500
#define BP_SERVO_US_MAX            1900
#define BP_SERVO_MAX_DEFLECT_US    320
#define BP_SERVO_MAX_SLEW_US_PER_TICK 30
#define BP_RUDDER_MAX_ANGLE_DEG    32.0f
#define BP_HIGH_SPEED_RUDDER_SCALE 0.650f

// -- ESC / throttle --
#define BP_ESC_US_MIN              1000
#define BP_ESC_US_IDLE             1100
#define BP_ESC_US_MAX              2000
#define BP_ESC_EFFECTIVE_MAX_US    1362
#define BP_ESC_ARM_US              1000
#define BP_ESC_ARM_TIME_MS         2500
#define BP_ESC_MAX_SLEW_US_PER_TICK 12
#define BP_THROTTLE_SCALE          0.2914f

// -- derived performance (m/s) --
#define BP_HULL_SPEED_MPS          1.250f
#define BP_PROP_MAX_SPEED_MPS      4.718f
#define BP_RECOMMENDED_MAX_MPS     1.375f

// -- control / PID seeds (STARTING POINTS, tune on water) --
#define BP_YAW_RATE_MAX_DPS        45.0f
#define BP_PID_HEADING_KP          2.000f
#define BP_PID_HEADING_KI          0.060f
#define BP_PID_HEADING_KD          0.030f
#define BP_PID_YAWRATE_KP          2.600f
#define BP_PID_YAWRATE_KI          0.250f
#define BP_PID_YAWRATE_KD          0.020f
#define BP_PID_SPEED_KP            1.500f
#define BP_PID_SPEED_KI            0.364f

// -- safety / tilt limits --
#define BP_MAX_ABS_ROLL_DEG        33.0f
#define BP_MAX_ABS_PITCH_DEG       19.8f

// -- transmitter / receiver --
#define BP_RC_MIN_US               1000
#define BP_RC_MID_US               1500
#define BP_RC_MAX_US               2000
#define BP_CH_THROTTLE             2
#define BP_CH_STEERING             1
#define BP_CH_MODE                 5
#define BP_CH_ARM                  6

// ---------------------------------------------------------------------------
// Runtime profile + input-shaping helpers (defined in boat_profile.c).
// ---------------------------------------------------------------------------
typedef struct {
  uint16_t rc_min_us;
  uint16_t rc_mid_us;
  uint16_t rc_max_us;
  uint8_t  ch_throttle;
  uint8_t  ch_steering;
  uint8_t  ch_mode;
  uint8_t  ch_arm;
  float    throttle_deadband;
  float    steering_deadband;
  float    throttle_expo;
  float    steering_expo;
  bool     throttle_reversed;
  bool     steering_reversed;
  uint16_t failsafe_throttle_us;
  uint16_t failsafe_steering_us;
  float    throttle_scale;
  float    high_speed_rudder_scale;
} BoatProfile;

#ifdef __cplusplus
extern "C" {
#endif

extern const BoatProfile BOAT_PROFILE;

// Map a raw RC pulse (us) to a centered, normalized [-1, 1] axis.
float bp_rc_us_to_norm(uint16_t us, uint16_t lo, uint16_t mid, uint16_t hi, bool reversed);

// Map a raw RC pulse (us) to a unipolar [0, 1] axis (e.g. throttle).
float bp_rc_us_to_unit(uint16_t us, uint16_t lo, uint16_t hi, bool reversed);

// Apply a center deadband then cubic expo to a [-1, 1] input.
float bp_apply_deadband_expo(float x, float deadband, float expo);

// Convenience: full throttle/steering pipeline from raw pulse to command.
float bp_shape_throttle(uint16_t pulse_us);
float bp_shape_steering(uint16_t pulse_us);

#ifdef __cplusplus
}
#endif

#endif  // BOAT_PROFILE_H
