// === GENERATED by generate_boat_profile.py on 2026-06-16 10:38:13 ===
// profile: default-displacement   hull: displacement
// DO NOT EDIT BY HAND -- regenerate from the boat spec instead.
//
// ----- derived report -------------------------------------------------------
//   pack voltage (nom/full) : 11.10 V / 12.60 V
//   motor rpm (no load)     :    13320 rpm
//   prop rpm (loaded)       :    10922 rpm
//   prop-limited max speed  :   4.72 m/s (  9.2 kn)
//   hull speed              :   1.25 m/s (  2.4 kn)
//   recommended max speed   :   1.38 m/s (  2.7 kn)
//   Froude number @ max     :   0.44
//   throttle scale applied  :  0.291  (ESC top capped to 1362 us)
// ----------------------------------------------------------------------------

#include "boat_profile.h"
#include <math.h>

const BoatProfile BOAT_PROFILE = {
  .rc_min_us             = 1000,
  .rc_mid_us             = 1500,
  .rc_max_us             = 2000,
  .ch_throttle           = 2,
  .ch_steering           = 1,
  .ch_mode               = 5,
  .ch_arm                = 6,
  .throttle_deadband     = 0.0400f,
  .steering_deadband     = 0.0500f,
  .throttle_expo         = 0.2000f,
  .steering_expo         = 0.3500f,
  .throttle_reversed     = false,
  .steering_reversed     = false,
  .failsafe_throttle_us  = 1000,
  .failsafe_steering_us  = 1500,
  .throttle_scale        = 0.2914f,
  .high_speed_rudder_scale = 0.6500f,
};

static float bp_clampf(float v, float lo, float hi) {
  return (v < lo) ? lo : ((v > hi) ? hi : v);
}

float bp_rc_us_to_norm(uint16_t us, uint16_t lo, uint16_t mid, uint16_t hi, bool reversed) {
  float v = (float)us;
  float out;
  if (v >= (float)mid) {
    float span = (float)hi - (float)mid;
    out = (span > 1.0f) ? (v - (float)mid) / span : 0.0f;
  } else {
    float span = (float)mid - (float)lo;
    out = (span > 1.0f) ? (v - (float)mid) / span : 0.0f;
  }
  out = bp_clampf(out, -1.0f, 1.0f);
  return reversed ? -out : out;
}

float bp_rc_us_to_unit(uint16_t us, uint16_t lo, uint16_t hi, bool reversed) {
  float span = (float)hi - (float)lo;
  float out = (span > 1.0f) ? ((float)us - (float)lo) / span : 0.0f;
  out = bp_clampf(out, 0.0f, 1.0f);
  return reversed ? (1.0f - out) : out;
}

float bp_apply_deadband_expo(float x, float deadband, float expo) {
  x = bp_clampf(x, -1.0f, 1.0f);
  float sign = (x < 0.0f) ? -1.0f : 1.0f;
  float a = fabsf(x);
  if (a <= deadband) {
    return 0.0f;
  }
  float denom = 1.0f - deadband;
  a = (denom > 1e-6f) ? (a - deadband) / denom : 0.0f;
  float shaped = (1.0f - expo) * a + expo * a * a * a;
  return sign * shaped;
}

float bp_shape_throttle(uint16_t pulse_us) {
  float u = bp_rc_us_to_unit(pulse_us, BOAT_PROFILE.rc_min_us, BOAT_PROFILE.rc_max_us,
                             BOAT_PROFILE.throttle_reversed);
  // expo on a unipolar axis: blend linear with cubic.
  float db = BOAT_PROFILE.throttle_deadband;
  if (u <= db) {
    u = 0.0f;
  } else {
    float denom = 1.0f - db;
    u = (denom > 1e-6f) ? (u - db) / denom : 0.0f;
  }
  float e = BOAT_PROFILE.throttle_expo;
  float shaped = (1.0f - e) * u + e * u * u * u;
  return bp_clampf(shaped * BOAT_PROFILE.throttle_scale, 0.0f, 1.0f);
}

float bp_shape_steering(uint16_t pulse_us) {
  float n = bp_rc_us_to_norm(pulse_us, BOAT_PROFILE.rc_min_us, BOAT_PROFILE.rc_mid_us,
                             BOAT_PROFILE.rc_max_us, BOAT_PROFILE.steering_reversed);
  return bp_apply_deadband_expo(n, BOAT_PROFILE.steering_deadband, BOAT_PROFILE.steering_expo);
}
